version: 2.1

jobs:
  test:
    working_directory: ~/vise
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkuout
      - run:
          command: |
            pip install -r requirements.txt
            pip install --quiet pytest
            echo "Run pytest."
            pytest vise
            echo "--- Done ---"

workflows:
  version: 2
  main:
    jobs:
      - test
