version: 2

jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/vise
    environment:
      PMG_DEFAULT_FUNCTIONAL: PBE_54
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          command: |
            ls $HOME/vise/vise/test_files/potcars
      - run:
          command: |
            echo 'PMG_VASP_PSP_DIR: ~/vise/vise/test_files/potcars' > $HOME/.pmgrc.yaml
            echo 'PMG_DEFAULT_FUNCTIONAL: PBE_54' >> $HOME/.pmgrc.yaml
            echo "PMG_MAPI_KEY: ${KEY}" >> $HOME/.pmgrc.yaml
      - run:
          command: |
            cat $HOME/.pmgrc.yaml
      - run:
          command: |
            sudo pip install -r requirements.txt
            sudo pip install --quiet pytest pytest-cov
            pytest vise --cov=vise --cov-report html:coverage_reports vise

#
#workflows:
#  version: 2
#  main:
#    jobs:
#      - build:
#        filters:
#          branches:
#            only: master
